// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDateTime = new DateTime(2022, 7, 26, 12, 5, 42, 246, DateTimeKind.Local).AddTicks(3608),
                            Password = "12345",
                            UserName = "UserName 1"
                        },
                        new
                        {
                            Id = 2,
                            InsertDateTime = new DateTime(2022, 7, 26, 12, 5, 42, 246, DateTimeKind.Local).AddTicks(3731),
                            Password = "12345",
                            UserName = "UserName 2"
                        },
                        new
                        {
                            Id = 3,
                            InsertDateTime = new DateTime(2022, 7, 26, 12, 5, 42, 246, DateTimeKind.Local).AddTicks(3757),
                            Password = "12345",
                            UserName = "UserName 3"
                        },
                        new
                        {
                            Id = 4,
                            InsertDateTime = new DateTime(2022, 7, 26, 12, 5, 42, 246, DateTimeKind.Local).AddTicks(3781),
                            Password = "12345",
                            UserName = "UserName 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
